### PR TITLE
Ability to use multiple instances of same tag key

### LINKED ISSUE #491: Powerpipe uses only the last value when using `--tag` multiple times
**Describe the bug**
When using the `--tag` flag with `powerpipe benchmark run` or `powerpipe control run`, only the last value is considered.

**Powerpipe version (`powerpipe -v`)**
v0.4.0

**To reproduce**
`powerpipe benchmark run benchmark.infra_compliance --dry-run --database sqlite://:memory: --tag service=AWS/S3 --tag service=GCP/Storage`

**Expected behavior**
All controls for GCP as well as AWS should run. Only the GCP controls are running.

### PR DESCRIPTION
**Pull request by binaek**
Fixes https://github.com/turbot/powerpipe/issues/491

### CODE REVIEW

**Comment by kaidaguerre** [comment]
@binaek please rebase

**Comment by binaek** [comment]
> @binaek please rebase

@kaidaguerre done

**Comment by binaek** [comment]
Replaced with https://github.com/turbot/pipe-fittings/pull/581

**Comment by binaek** [comment]
cc @kaidaguerre ^^^

**Pull request closed without merging**
